<ref *2> Guild {
  id: '1013536413310001172',
  name: 'Splooners',
  icon: 'b90508bfce3722ae05b4cf63fb592c1d',
  features: [],
  commands: <ref *1> GuildApplicationCommandManager {
    permissions: ApplicationCommandPermissionsManager {
      manager: [Circular *1],
      guild: [Circular *2],
      guildId: '1013536413310001172',
      commandId: null
    },
    guild: [Circular *2]
  },
  members: GuildMemberManager { guild: [Circular *2] },
  channels: GuildChannelManager { guild: [Circular *2] },
  bans: GuildBanManager { guild: [Circular *2] },
  roles: RoleManager { guild: [Circular *2] },
  presences: PresenceManager {},
  voiceStates: VoiceStateManager { guild: [Circular *2] },
  stageInstances: StageInstanceManager { guild: [Circular *2] },
  invites: GuildInviteManager { guild: [Circular *2] },
  scheduledEvents: GuildScheduledEventManager { guild: [Circular *2] },
  available: true,
  shardId: 0,
  splash: null,
  banner: null,
  description: null,
  verificationLevel: 0,
  vanityURLCode: null,
  nsfwLevel: 0,
  premiumSubscriptionCount: 0,
  discoverySplash: null,
  memberCount: 2,
  large: false,
  premiumProgressBarEnabled: false,
  applicationId: null,
  afkTimeout: 300,
  afkChannelId: '1013540155115708566',
  systemChannelId: '1013539474006876323',
  premiumTier: 0,
  widgetEnabled: null,
  widgetChannelId: null,
  explicitContentFilter: 0,
  mfaLevel: 0,
  joinedTimestamp: 1661718158530,
  defaultMessageNotifications: 1,
  systemChannelFlags: SystemChannelFlagsBitField { bitfield: 0 },
  maximumMembers: 500000,
  maximumPresences: null,
  maxVideoChannelUsers: 25,
  approximateMemberCount: null,
  approximatePresenceCount: null,
  vanityURLUses: null,
  rulesChannelId: null,
  publicUpdatesChannelId: null,
  preferredLocale: 'en-US',
  ownerId: '666727743706234928',
  emojis: GuildEmojiManager { guild: [Circular *2] },
  stickers: GuildStickerManager { guild: [Circular *2] }
}